### ISSUE TITLE
no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by sonalkr132** [brigade/haml-lint#101]
I update my haml-lint from `0.11.0` to `0.15.2` and got following error:
```
no implicit conversion of String into Integer
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration.rb:104:in `[]'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration.rb:104:in `block (2 levels) in ensure_linter_include_exclude_arrays_exist'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration.rb:102:in `each'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration.rb:102:in `block in ensure_linter_include_exclude_arrays_exist'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration.rb:101:in `each'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration.rb:101:in `ensure_linter_include_exclude_arrays_exist'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration.rb:84:in `validate'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration.rb:17:in `initialize'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration_loader.rb:68:in `new'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration_loader.rb:68:in `load_from_file'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration_loader.rb:34:in `load_file'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/configuration_loader.rb:18:in `load_applicable_config'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/runner.rb:40:in `load_applicable_config'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/runner.rb:15:in `run'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/cli.rb:82:in `scan_for_lints'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/cli.rb:51:in `act_on_options'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/lib/haml_lint/cli.rb:23:in `run'
/home/addie/.rvm/gems/ruby-2.2.1/gems/haml_lint-0.15.2/bin/haml-lint:7:in `<top (required)>'
/home/addie/.rvm/gems/ruby-2.2.1/bin/haml-lint:23:in `load'
/home/addie/.rvm/gems/ruby-2.2.1/bin/haml-lint:23:in `<main>'
/home/addie/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/addie/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Here is my Gemfile.lock
```
GIT
  remote: git://github.com/sonalkr132/ratyrate.git
  revision: b705610b3c6f896f788519df23b289e6c81252fe
  branch: refactoring
  specs:
    ratyrate (1.2.2.alpha)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.1.9)
      actionpack (= 4.1.9)
      actionview (= 4.1.9)
      mail (~> 2.5, >= 2.5.4)
    actionpack (4.1.9)
      actionview (= 4.1.9)
      activesupport (= 4.1.9)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    actionpack-action_caching (1.1.1)
      actionpack (>= 4.0.0, < 5.0)
    actionview (4.1.9)
      activesupport (= 4.1.9)
      builder (~> 3.1)
      erubis (~> 2.7.0)
    activemodel (4.1.9)
      activesupport (= 4.1.9)
      builder (~> 3.1)
    activerecord (4.1.9)
      activemodel (= 4.1.9)
      activesupport (= 4.1.9)
      arel (~> 5.0.0)
    activerecord-session_store (0.1.1)
      actionpack (>= 4.0.0, < 5)
      activerecord (>= 4.0.0, < 5)
      railties (>= 4.0.0, < 5)
    activesupport (4.1.9)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    acts-as-taggable-on (3.5.0)
      activerecord (>= 3.2, < 5)
    addressable (2.3.7)
    ancestry (2.1.0)
      activerecord (>= 3.0.0)
    arel (5.0.1.20140414130214)
    ast (2.0.0)
    astrolabe (1.3.0)
      parser (>= 2.2.0.pre.3, < 3.0)
    axiom-types (0.1.1)
      descendants_tracker (~> 0.0.4)
      ice_nine (~> 0.11.0)
      thread_safe (~> 0.3, >= 0.3.1)
    bcrypt (3.1.10)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.2.2)
    cancancan (1.10.1)
    capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-webkit (1.4.1)
      capybara (>= 2.3.0, < 2.5.0)
      json
    celluloid (0.16.0)
      timers (~> 4.0.0)
    coderay (1.1.0)
    coercible (1.0.0)
      descendants_tracker (~> 0.0.1)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.3.0)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1)
    database_cleaner (1.4.1)
    debug_inspector (0.0.2)
    delayed_job (4.0.6)
      activesupport (>= 3.0, < 5.0)
    delayed_job_active_record (4.0.3)
      activerecord (>= 3.0, < 5.0)
      delayed_job (>= 3.0, < 4.1)
    descendants_tracker (0.0.4)
      thread_safe (~> 0.3, >= 0.3.1)
    devise (3.4.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    diff-lcs (1.2.5)
    equalizer (0.0.11)
    erubis (2.7.0)
    escape (0.0.4)
    execjs (2.4.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faker (1.4.3)
      i18n (~> 0.5)
    faraday (0.9.1)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.6)
    formatador (0.2.5)
    gitlab-grack (2.0.2)
      rack (~> 1.5.1)
    grape (0.12.0)
      activesupport
      builder
      hashie (>= 2.1.0)
      multi_json (>= 1.3.2)
      multi_xml (>= 0.5.2)
      rack (>= 1.3.0)
      rack-accept
      rack-mount
      virtus (>= 1.0.0)
    guard (2.12.4)
      formatador (>= 0.2.4)
      listen (~> 2.7)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-rspec (4.5.0)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    guard-rubocop (1.2.0)
      guard (~> 2.0)
      rubocop (~> 0.20)
    haml (4.0.6)
      tilt
    haml_lint (0.15.2)
      haml (~> 4.0)
      rubocop (>= 0.25.0)
      sysexits (~> 1.1)
    hashie (3.4.0)
    hike (1.2.3)
    hitimes (1.2.2)
    i18n (0.7.0)
    ice_nine (0.11.1)
    jquery-rails (3.1.2)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-turbolinks (2.1.0)
      railties (>= 3.1.0)
      turbolinks
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.2)
    jwt (1.4.1)
    kgio (2.9.3)
    launchy (2.4.3)
      addressable (~> 2.3)
    libv8 (3.16.14.7)
    listen (2.9.0)
      celluloid (>= 0.15.2)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    lumberjack (1.0.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    method_source (0.8.2)
    mime-types (2.4.3)
    mini_portile (0.6.2)
    minitest (5.5.1)
    multi_json (1.11.0)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    nenv (0.2.0)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    notiffany (0.0.6)
      nenv (~> 0.1)
      shellany (~> 0.0)
    nprogress-rails (0.1.6.6)
    oa-core (0.3.2)
    oa-openid (0.3.2)
      oa-core (= 0.3.2)
      rack-openid (~> 1.3.1)
      ruby-openid-apps-discovery (~> 1.2.0)
    oauth (0.4.7)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    omniauth (1.2.2)
      hashie (>= 1.2, < 4)
      rack (~> 1.0)
    omniauth-facebook (2.0.1)
      omniauth-oauth2 (~> 1.2)
    omniauth-github (1.1.2)
      omniauth (~> 1.0)
      omniauth-oauth2 (~> 1.1)
    omniauth-linkedin (0.2.0)
      omniauth-oauth (~> 1.0)
    omniauth-oauth (1.0.1)
      oauth
      omniauth (~> 1.0)
    omniauth-oauth2 (1.2.0)
      faraday (>= 0.8, < 0.10)
      multi_json (~> 1.3)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    omniauth-openid (1.0.1)
      omniauth (~> 1.0)
      rack-openid (~> 1.3.1)
    omniauth-twitter (1.1.0)
      multi_json (~> 1.3)
      omniauth-oauth (~> 1.0)
    orm_adapter (0.5.0)
    paranoia (2.1.0)
      activerecord (~> 4.0)
    parser (2.2.0.3)
      ast (>= 1.1, < 3.0)
    pg (0.18.3)
    pg_search (1.0.5)
      activerecord (>= 3.1)
      activesupport (>= 3.1)
      arel
    power_assert (0.2.3)
    powerpack (0.1.0)
    pry (0.10.1)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    rack (1.5.2)
    rack-accept (0.4.5)
      rack (>= 0.4)
    rack-mount (0.8.3)
      rack (>= 1.0.0)
    rack-openid (1.3.1)
      rack (>= 1.1.0)
      ruby-openid (>= 2.1.8)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.1.9)
      actionmailer (= 4.1.9)
      actionpack (= 4.1.9)
      actionview (= 4.1.9)
      activemodel (= 4.1.9)
      activerecord (= 4.1.9)
      activesupport (= 4.1.9)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.9)
      sprockets-rails (~> 2.0)
    rails-observers (0.1.2)
      activemodel (~> 4.0)
    railties (4.1.9)
      actionpack (= 4.1.9)
      activesupport (= 4.1.9)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.0.0)
    raindrops (0.15.0)
    rake (10.4.2)
    rb-fsevent (0.9.4)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    redcarpet (3.2.2)
    ref (1.0.5)
    responders (1.1.2)
      railties (>= 3.2, < 4.2)
    rmagick (2.13.4)
    rspec (3.2.0)
      rspec-core (~> 3.2.0)
      rspec-expectations (~> 3.2.0)
      rspec-mocks (~> 3.2.0)
    rspec-core (3.2.2)
      rspec-support (~> 3.2.0)
    rspec-expectations (3.2.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.2.0)
    rspec-mocks (3.2.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.2.0)
    rspec-rails (3.2.1)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.2.0)
      rspec-expectations (~> 3.2.0)
      rspec-mocks (~> 3.2.0)
      rspec-support (~> 3.2.0)
    rspec-support (3.2.2)
    rubocop (0.29.1)
      astrolabe (~> 1.3)
      parser (>= 2.2.0.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.4)
    ruby-openid (2.7.0)
    ruby-openid-apps-discovery (1.2.0)
      ruby-openid (>= 2.1.7)
    ruby-progressbar (1.7.1)
    rugged (0.21.4)
    sass (3.4.13)
    sass-rails (5.0.1)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
    sass-rails-source-maps (0.1.0)
      rails
      sass (~> 3.3)
      sass-rails (~> 5.0.0.beta1)
      sprockets (>= 2.3.0)
    shellany (0.0.1)
    shoulda-matchers (2.8.0)
      activesupport (>= 3.0.0)
    sketchily (4.0.1)
      nokogiri
      rails (>= 3.1)
    slop (3.6.0)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.2.4)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sysexits (1.2.0)
    test-unit (3.0.9)
      power_assert
    therubyracer (0.12.1)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    timers (4.0.1)
      hitimes
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unicorn (4.9.0)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    virtus (1.0.5)
      axiom-types (~> 0.1)
      coercible (~> 1.0)
      descendants_tracker (~> 0.0, >= 0.0.3)
      equalizer (~> 0.0, >= 0.0.9)
    warden (1.2.3)
      rack (>= 1.0)
    will_paginate (3.0.7)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  actionpack-action_caching
  activerecord-session_store
  acts-as-taggable-on (~> 3.4)
  ancestry (~> 2.1.0)
  better_errors
  binding_of_caller
  cancancan (~> 1.10)
  capybara
  capybara-webkit (~> 1.4.1)
  coffee-rails
  database_cleaner (~> 1.4.1)
  delayed_job_active_record (~> 4.0.3)
  devise
  escape
  factory_girl_rails
  faker
  gitlab-grack (~> 2.0.2)
  grape
  guard-rspec
  guard-rubocop (~> 1.2.0)
  haml
  haml_lint
  jquery-rails
  jquery-turbolinks
  jquery-ui-rails
  launchy
  minitest
  nprogress-rails
  oa-openid
  omniauth
  omniauth-facebook
  omniauth-github
  omniauth-linkedin
  omniauth-openid
  omniauth-twitter
  paranoia (~> 2.0)
  pg
  pg_search
  rails (~> 4.1.0)
  rails-observers
  rake
  ratyrate!
  redcarpet
  rmagick (~> 2.13.4)
  rspec-rails
  rubocop
  rugged (~> 0.21)
  sass-rails
  sass-rails-source-maps
  shoulda-matchers
  sketchily
  test-unit
  therubyracer
  turbolinks
  uglifier
  unicorn
  will_paginate

BUNDLED WITH
   1.10.6
```
I am using rubocop `0.29.1`, haml `4.0.6` and here is my `ruby -v`
```
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

**Comment by sds** [comment]
Hey @sonalkr132,

Since this error is occurring in the `Configuration` class, can you include the configuration you are using? My hunch is that you are using an array for your `linters` configuration instead of a hash, but I would need to see your configuration file to be sure. Thanks!

**Comment by sonalkr132** [comment]
I got around the problem. Following works:
```
linters:
  LineLength:
    max: 100
  UnnecessaryStringOutput:
    exclude:
      - '**/*.js.haml'
```
However, following gives the error:
```
linters:
  LineLength:
    max: 100
  exclude:
    - '**/*.js.haml'
```

**Comment by sonalkr132** [comment]
oh wait! [Here](https://github.com/brigade/haml-lint/issues/78#issuecomment-112840051) you said that `exclude` should not be nested. So following works:
```
linters:
  LineLength:
    max: 100
exclude:
  - '**/*.js.haml'
```
