### ISSUE TITLE
Bug while running haml-lint

### ISSUE THREAD

**Issue by justinelam** [brigade/haml-lint#102]
```
undefined method `-' for nil:NilClass
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/linter/space_before_script.rb:29:in `visit_tag'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:18:in `visit'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `block in visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `each'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:23:in `visit'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `block in visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `each'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:23:in `visit'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `block in visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `each'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:23:in `visit'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `block in visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `each'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:23:in `visit'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/linter.rb:17:in `run'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:63:in `block in find_lints'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:62:in `each'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:62:in `find_lints'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:22:in `block in run'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:21:in `each'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:21:in `run'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/cli.rb:73:in `scan_for_lints'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/cli.rb:47:in `act_on_options'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/lib/haml_lint/cli.rb:22:in `run'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml-lint-0.13.0/bin/haml-lint:7:in `<top (required)>'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/bin/haml-lint:23:in `load'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/bin/haml-lint:23:in `<main>'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `eval'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by sds** [comment]
Hey @justinelam, thanks for the report.

It looks like you're running an older version of `haml-lint`. Can I get you to upgrade to the latest version (0.15.2 at time of writing) and try again?

If you're still seeing the problem, could you include the snippet of HAML code that reproduces the issue? It will make finding the cause of the problem easier. Thanks!

**Comment by sds** [comment]
Closing due to lack of response.
