### ISSUE TITLE
undefined method `type' for false:FalseClass

### ISSUE THREAD

**Issue by tjchambers** [brigade/haml-lint#127]
```
~/projects/aot@pro2 [07:43:21]> haml-lint app/views
undefined method `type' for false:FalseClass
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/linter/unnecessary_string_output.rb:34:in `outputs_string_literal?'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/linter/unnecessary_string_output.rb:25:in `visit_script'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:18:in `visit'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `block in visit_children'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `each'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `visit_children'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:23:in `visit'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/linter.rb:17:in `run'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:63:in `block in find_lints'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:62:in `each'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:62:in `find_lints'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:22:in `block in run'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:21:in `each'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:21:in `run'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/cli.rb:73:in `scan_for_lints'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/cli.rb:47:in `act_on_options'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/lib/haml_lint/cli.rb:22:in `run'
/Users/tj/.rvm/gems/ruby-2.2.4@global/gems/haml-lint-0.13.0/bin/haml-lint:7:in `<top (required)>'
/Users/tj/.rvm/gems/ruby-2.2.4@global/bin/haml-lint:23:in `load'
/Users/tj/.rvm/gems/ruby-2.2.4@global/bin/haml-lint:23:in `<main>'
/Users/tj/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `eval'
/Users/tj/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `<main>'
Report this bug at https://github.com/brigade/haml-lint/issues
```

**Comment by sds** [comment]
Hey @tjchambers, thanks for the report.

It looks like you're running an older version of HAML-Lint. Make sure you `gem install haml_lint` (with an underscore) and not `haml-lint` so that you get the latest version (we switched names in order to follow proper [RubyGems naming conventions](http://guides.rubygems.org/name-your-gem/)).

**Comment by tjchambers** [comment]
I have to say that was not obvious - and I just installed it today. The gem is named one thing and the command another. Hmmm

**Comment by sds** [comment]
Totally agree it's a source of confusion. Unfortunately I can't yank the old gem as there are still a large number of `Gemfile`s out in the wild that refer to the hyphened gem name.

Hyphens are easier to type (no shift required on QWERTY keyboards) and thus lend themselves better to executable names/commands. As for why underscores are preferred for the gem name, you'll have to take that battle up with the RubyGems team, as it's their [convention](http://guides.rubygems.org/name-your-gem/).

Thanks for your feedback.
