### ISSUE TITLE
Error encountered while executing the command - `method_missing': undefined method `this' for #<Gem::

### ISSUE THREAD

**Issue by samar-mishra** [brigade/haml-lint#135]
```
haml-lint app/views/spree/checkout/_mobile.html.haml
/Users/Topform/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2159:in `method_missing': undefined method `this' for #<Gem::Specification:0x3feb4545e690 haml-4.0.5> (NoMethodError)
	from /Users/Topform/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/Topform/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/gems/haml_lint-0.17.1/lib/haml_lint.rb:2:in `<top (required)>'
	from /Users/Topform/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /Users/Topform/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /Users/Topform/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/gems/haml_lint-0.17.1/bin/haml-lint:3:in `<top (required)>'
	from /Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/bin/haml-lint:22:in `load'
	from /Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/bin/haml-lint:22:in `<main>'
	from /Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sds** [comment]
Hey @samar-mishra,

This is not a problem with HAML-Lint. See https://github.com/rubygems/rubygems/issues/1420 for information on the bug.
