### ISSUE TITLE
A blank value for Rubocop/ignored_cops raises an exception

### ISSUE THREAD

**Issue by shepmaster** [brigade/haml-lint#139]
```yaml
linters:
  RuboCop:
    enabled: true
    ignored_cops:
```

Produces this:

```
$ haml-lint app/views/
undefined method `include?' for nil:NilClass
gems/haml_lint-0.17.1/lib/haml_lint/linter/rubocop.rb:63:in `block in extract_lints_from_offenses'
gems/haml_lint-0.17.1/lib/haml_lint/linter/rubocop.rb:63:in `select'
gems/haml_lint-0.17.1/lib/haml_lint/linter/rubocop.rb:63:in `extract_lints_from_offenses'
gems/haml_lint-0.17.1/lib/haml_lint/linter/rubocop.rb:38:in `block in find_lints'
lib/ruby/2.3.0/tempfile.rb:295:in `open'
gems/haml_lint-0.17.1/lib/haml_lint/linter/rubocop.rb:34:in `find_lints'
gems/haml_lint-0.17.1/lib/haml_lint/linter/rubocop.rb:16:in `visit_root'
gems/haml_lint-0.17.1/lib/haml_lint/haml_visitor.rb:38:in `safe_send'
gems/haml_lint-0.17.1/lib/haml_lint/haml_visitor.rb:17:in `visit'
gems/haml_lint-0.17.1/lib/haml_lint/linter.rb:28:in `run'
gems/haml_lint-0.17.1/lib/haml_lint/runner.rb:58:in `block in collect_lints'
gems/haml_lint-0.17.1/lib/haml_lint/runner.rb:57:in `map'
gems/haml_lint-0.17.1/lib/haml_lint/runner.rb:57:in `collect_lints'
gems/haml_lint-0.17.1/lib/haml_lint/runner.rb:21:in `block in run'
gems/haml_lint-0.17.1/lib/haml_lint/runner.rb:20:in `map'
gems/haml_lint-0.17.1/lib/haml_lint/runner.rb:20:in `run'
gems/haml_lint-0.17.1/lib/haml_lint/cli.rb:82:in `scan_for_lints'
gems/haml_lint-0.17.1/lib/haml_lint/cli.rb:51:in `act_on_options'
gems/haml_lint-0.17.1/lib/haml_lint/cli.rb:23:in `run'
gems/haml_lint-0.17.1/bin/haml-lint:7:in `<top (required)>'
bin/haml-lint:23:in `load'
bin/haml-lint:23:in `<main>'
bin/ruby_executable_hooks:15:in `eval'
bin/ruby_executable_hooks:15:in `<main>'
```

A workaround is to not specify `ignored_cops` at all.

**Comment by sds** [comment]
Specifying an empty `ignore_cops` list is definitely _not_ recommended. You'll get all kind of nonsense warnings due to the way HAML-Lint extracts Ruby code to pass into RuboCop.

In any case, I've added support for gracefully handling this in 778e9116aa188596020b4bdfc3ff58881e2da824. Thanks for the report!
