### ISSUE TITLE
Starting Problem with ruby 2.3.1

### ISSUE THREAD

**Issue by Datyv** [brigade/haml-lint#151]
When I run any haml-lint command I'm getting this error. Anyone seen this before? 

```datyv@mycom:~/rails/buddy$ haml-lint -v
/home/datyv/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0xff69dc haml_lint-0.18.1> (NoMethodError)
	from /home/datyv/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /home/datyv/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /home/datyv/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.18.1/bin/haml-lint:3:in `<top (required)>'
	from /home/datyv/.rvm/gems/ruby-2.3.1/bin/haml-lint:23:in `load'
	from /home/datyv/.rvm/gems/ruby-2.3.1/bin/haml-lint:23:in `<main>'
	from /home/datyv/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/datyv/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by sds** [comment]
Hey @Datyv,

This problem is due to a bug introduced in RubyGems and is unrelated to HAML-Lint. You can find out more at https://github.com/rubygems/rubygems/issues/1420. 

Hope that helps!
