### ISSUE TITLE
Does not work with rubocop-0.44.0

### ISSUE THREAD

**Issue by Bjoernsen** [brigade/haml-lint#158]
Today, there was a new release of rubocop (rubocop-0.44.0). Now, I am not able to run `haml-lint` anymore.

with rubocop 0.43
```shell
$ gem install haml_lint --no-ri --no-rdoc
Successfully installed tilt-2.0.5

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Successfully installed haml-4.0.7
Successfully installed rainbow-2.1.0
Successfully installed ast-2.3.0
Successfully installed parser-2.3.1.4
Successfully installed powerpack-0.1.1
Successfully installed ruby-progressbar-1.8.1
Successfully installed unicode-display_width-1.1.1
Successfully installed rubocop-0.43.0
Successfully installed sysexits-1.2.0
Successfully installed haml_lint-0.18.2
11 gems installed
$ haml-lint app/views/
```

with rubocop 0.44
```shell
$ gem install haml_lint --no-ri --no-rdoc
Successfully installed tilt-2.0.5

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Successfully installed haml-4.0.7
Successfully installed rainbow-2.1.0
Successfully installed ast-2.3.0
Successfully installed parser-2.3.1.4
Successfully installed powerpack-0.1.1
Successfully installed ruby-progressbar-1.8.1
Successfully installed unicode-display_width-1.1.1
Successfully installed rubocop-0.44.0
Successfully installed sysexits-1.2.0
Successfully installed haml_lint-0.18.2
11 gems installed
$ haml-lint app/views/
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/rubocop-0.44.0/lib/rubocop/cop/performance/case_when_splat.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/rubocop-0.44.0/lib/rubocop.rb:161:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/haml_lint-0.18.2/lib/haml_lint/ruby_parser.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/haml_lint-0.18.2/lib/haml_lint.rb:12:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/haml_lint-0.18.2/bin/haml-lint:3:in `<top (required)>'
	from /usr/local/bundle/bin/haml-lint:22:in `load'
	from /usr/local/bundle/bin/haml-lint:22:in `<main>'
```

**Comment by Bjoernsen** [comment]
It seems there was a :bug: in rubocop. Everything works with `rubocop-0.44.1`.
