### ISSUE TITLE
Failure with HAML v5.0.1: "undefined method `each' for nil:NilClass" in "contains_class_attribute?"

### ISSUE THREAD

**Issue by andyw8** [brigade/haml-lint#247]
I'm upgrading from HAML v4.0.7 to v5.0.1, and running into this failure:

```
$ bundle exec haml-lint
undefined method `each' for nil:NilClass
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:33:in `contains_class_attribute?'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:24:in `visit_tag'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/haml_visitor.rb:40:in `safe_send'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/haml_visitor.rb:19:in `visit'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/haml_visitor.rb:30:in `each'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/haml_visitor.rb:24:in `visit'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/linter.rb:28:in `run'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/runner.rb:84:in `block in collect_lints'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/runner.rb:83:in `map'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/runner.rb:83:in `collect_lints'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/runner.rb:119:in `process_file'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/runner.rb:108:in `block in process_files'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/runner.rb:107:in `each'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/runner.rb:107:in `process_files'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/runner.rb:132:in `report'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/runner.rb:23:in `run'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/cli.rb:106:in `scan_for_lints'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/cli.rb:51:in `act_on_options'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/cli.rb:23:in `run'
/Users/andy/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.24.0/bin/haml-lint:7:in `<top (required)>'
```

Setup:
```
- Haml-Lint version: 0.24.0
- Haml version: 5.0.1
- RuboCop version: 0.48.1
- Ruby version: 2.4.0
```

The branch can be viewed at https://github.com/andyw8/techradar/pull/40

**Comment by sds** [comment]
Hey @andyw8,

Support for HAML 5 landed in [0.25.0](https://github.com/brigade/haml-lint/releases/tag/v0.25.0). You're running HAML-Lint 0.24.0, which is why you're seeing this problem. Upgrade to the latest version (0.26.0 at time of writing) to fix this issue. Hope this helps!

**Comment by andyw8** [comment]
Ok, I guess the gemspec for 0.24.0 is wrong then (it specifies haml < 5.1, >= 4.0).

https://rubygems.org/gems/haml_lint/versions/0.24.0

**Comment by michaelherold** [comment]
Yeah, Haml changed some API between their 5.0.0.beta.2 release and 5.0.0. Our version 0.24.0 works with the beta, but not with the released version. That's why there's confusion.

You can see this in #231 if you're interested, @andyw8.
