### ISSUE TITLE
Error linting all files

### ISSUE THREAD

**Issue by aussiDavid** [brigade/haml-lint#260]
This happens when guard tries to lint all my HAML files.
I carn't tell which HAML file it is rasing the exception on.

```
09:24:46 - INFO - Running HAML-Lint for all haml files
undefined method `type' for nil:NilClass
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:42:in `static_class_attribute_value?'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:32:in `block (2 levels) in contains_class_attribute?'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:31:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:31:in `block in contains_class_attribute?'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:27:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:27:in `contains_class_attribute?'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:18:in `visit_tag'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:38:in `safe_send'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:17:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/linter.rb:28:in `run'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/runner.rb:58:in `block in collect_lints'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/runner.rb:57:in `map'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/runner.rb:57:in `collect_lints'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/runner.rb:21:in `block in run'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/runner.rb:20:in `map'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/runner.rb:20:in `run'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/cli.rb:82:in `scan_for_lints'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/cli.rb:51:in `act_on_options'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/lib/haml_lint/cli.rb:23:in `run'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.19.0/bin/haml-lint:7:in `<top (required)>'
/Users/David/.rvm/gems/ruby-2.3.1/bin/haml-lint:22:in `load'
/Users/David/.rvm/gems/ruby-2.3.1/bin/haml-lint:22:in `<main>'
/Users/David/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/David/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Report this bug at https://github.com/brigade/haml-lint/issues

To help fix this issue, please include:
- The above stack trace
- Haml-Lint version: 0.19.0
- Haml version: 4.0.7
- RuboCop version: 0.44.1
- Ruby version: 2.3.1
```

**Comment by sds** [comment]
Hey @aussiDavid, thanks for the report.

It looks like you're using a pretty old version of HAML-Lint (released in 2016). Can you try upgrading to the latest version and see if this issue still occurs?

If so, you can run `haml-lint` on selective parts of your codebase to narrow down which file it is.

**Comment by aussiDavid** [comment]
All good. Thanks.
