### ISSUE TITLE
undefined method `type' for nil:NilClass

### ISSUE THREAD

**Issue by aussiDavid** [brigade/haml-lint#264]
Hi all,

I'm getting this error when I run the linter on my entire rails project.

I carn't tell which file it is failing on.

```
undefined method `type' for nil:NilClass
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:48:in `static_class_attribute_value?'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:38:in `block (2 levels) in contains_class_attribute?'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:37:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:37:in `block in contains_class_attribute?'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:33:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:33:in `contains_class_attribute?'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:24:in `visit_tag'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:40:in `safe_send'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:19:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:24:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:24:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:24:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:24:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:24:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:24:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:24:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/haml_visitor.rb:24:in `visit'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/linter.rb:28:in `run'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/runner.rb:84:in `block in collect_lints'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/runner.rb:83:in `map'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/runner.rb:83:in `collect_lints'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/runner.rb:119:in `process_file'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/runner.rb:108:in `block in process_files'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/runner.rb:107:in `each'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/runner.rb:107:in `process_files'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/runner.rb:132:in `report'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/runner.rb:23:in `run'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/cli.rb:106:in `scan_for_lints'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/cli.rb:51:in `act_on_options'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/lib/haml_lint/cli.rb:23:in `run'
/Users/David/.rvm/gems/ruby-2.3.1/gems/haml_lint-0.26.0/bin/haml-lint:7:in `<top (required)>'
/Users/David/.rvm/gems/ruby-2.3.1/bin/haml-lint:23:in `load'
/Users/David/.rvm/gems/ruby-2.3.1/bin/haml-lint:23:in `<main>'
/Users/David/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/David/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Report this bug at https://github.com/brigade/haml-lint/issues

To help fix this issue, please include:
- The above stack trace
- Haml-Lint version: 0.26.0
- Haml version: 4.0.7
- RuboCop version: 0.50.0
- Ruby version: 2.3.1
```

**Comment by michaelherold** [comment]
Sorry for the trouble!

This one is going to be hard to debug with this amount of information. Would it be possible for you to track down a code snippet that is causing this failure?

I've done this in the past by running `haml-lint` on isolated folders of views, then pairing it down from there. For example:

```sh
bundle exec haml-lint app/views/admin
# => Success? Move on to the next folder
# => Failure? Run on a subfolder of app/views/admin
bundle exec haml-lint app/views/admin/my_controller
# => Repeat until you find a failing view
```

Once you find the failing view, you can comment out sections of the view to track it down to the block that is causing it to fail.

**Comment by aussiDavid** [comment]
Found it. The issue was this line.

```
%input{{:id => "property_application_additional_questions_attributes_#{i}_answer", class: ('lance-ujs-input-require' if agency_question.required?), "data-target": "#additional_question_#{agency_question.id}", :name => "property_application[additional_questions_attributes][#{i}][answer]", type: "radio", value: value}, question.answer == value ? { checked: "checked" } : {}}= label
```

There is a nested set {}'s. Oddly enough it HAML was still able to render this.
