### ISSUE TITLE
Malformed comment throws: undefined method `type' for nil:NilClass

### ISSUE THREAD

**Issue by joshlory** [brigade/haml-lint#82]
Great tool!  We hit a small bug with a malformed comment in our codebase.  Minimal repro:
```haml
=# bad comment
```

```
$ haml-lint -i UnnecessaryStringOutput bug.haml
undefined method `type' for nil:NilClass
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/linter/unnecessary_string_output.rb:34:in `outputs_string_literal?'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/linter/unnecessary_string_output.rb:25:in `visit_script'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/haml_visitor.rb:18:in `visit'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/haml_visitor.rb:27:in `block in visit_children'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/haml_visitor.rb:27:in `each'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/haml_visitor.rb:27:in `visit_children'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/haml_visitor.rb:23:in `visit'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/linter.rb:28:in `run'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/runner.rb:58:in `block in collect_lints'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/runner.rb:57:in `map'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/runner.rb:57:in `collect_lints'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/runner.rb:21:in `block in run'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/runner.rb:20:in `map'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/runner.rb:20:in `run'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/cli.rb:82:in `scan_for_lints'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/cli.rb:51:in `act_on_options'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/lib/haml_lint/cli.rb:23:in `run'
/Users/joshlory/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/haml_lint-0.14.1/bin/haml-lint:7:in `<top (required)>'
/Users/joshlory/.rbenv/versions/2.0.0-p481/bin/haml-lint:23:in `load'
/Users/joshlory/.rbenv/versions/2.0.0-p481/bin/haml-lint:23:in `<main>'
Report this bug at https://github.com/brigade/haml-lint/issues
```

**Comment by sds** [comment]
Thanks for the report, @joshlory.

Fixed in a9ce99409166c76abc8adb5a5d3ee287c49939c9.
